### ISSUE TITLE
Contact Form 7 integration (feature request)

### ISSUE THREAD

**Issue by jeffmcneill** [groucho75/alo-easymail#13]
I can do this as a plugin, but maybe you can help. The idea is to get the same kind of injection of the newsletter tick boxes into a CF7 form as you have done by injecting the newsletter tick boxes into a new user registration.

I started this as a Twitter discussion: https://twitter.com/jeffmcneill/status/739372111139987456

I will look into how you've implemented this on the Wordpress new user registration form. Of course it may be better to manually create the form in CF7 then have a plugin do the processing when certain named fields are detected (see pseudocode in this gist: https://gist.github.com/jeffmcneill/8bde6f8298c443c78cf1ff7e53f2b9cb )

**Comment by groucho75** [comment]
I updated your gist: https://gist.github.com/groucho75/1d44d76304ed6e2774a7a8c55a156fc0

**Comment by jeffmcneill** [comment]
Here is one with integrated instructions: https://gist.github.com/jeffmcneill/e7a53e11979ceddf81ec6c4764057c76

**Comment by groucho75** [comment]
Amazing!
Only a remark: in explaination, in step 1, I think it's better to write `/wp-content/mu-plugins/`.

**Comment by jeffmcneill** [comment]
Hi Alo,

The regular /wp-content/plugins/ directory works in a similar way for drop-in plugins, it is not identical. In the old days there was a /wp-content/mu-plugins/ in WPMU, and while that still works, it is redundant to /wp-content/plugins/ and also it doesn't actually work in the same way. originally set up for WPMU, it became something else later, and I think it may complicate things (see this page for reasons): https://codex.wordpress.org/Must_Use_Plugins

**Comment by jeffmcneill** [comment]
P.S., I suggest putting this file on your site and under the /developer or /faq area for people with this same need for CF7 integration.

**Comment by groucho75** [comment]
Hi Jeff, I've just added the link to the gist in developers page: http://www.eventualo.net/blog/easymail-newsletter-for-developers/#tutorial-addfromexternalforms
About the /wp-content/mu-plugins folder, it's useful in cases like this one when you need a piece of code automatically loaded (as adding the code inside theme functions.php, btw). Instead, if you put the file inside standard /wp-content/plugins/ you need to write a complete plugin (includign headers) and activate it using dashboard. Maybe too much for this kind of little integration.

**Comment by jeffmcneill** [comment]
Same here on OSX (but I can send, but it doesn't actually send in the Google Apps mailbox part). Sync appears to be broken for me. See also #2457

**Comment by jeffmcneill** [comment]
Hi Alo, you are correct of course. Not sure how I got confused. I've updated the file to reflect the change.
