### ISSUE TITLE
Add Dkim, SPF, Dmarc to FAQ

### ISSUE THREAD

**Issue by jeffmcneill** [groucho75/alo-easymail#14]
See this support thread for some info: https://wordpress.org/support/topic/dkim-signature-1?replies=2#post-8512058

**Comment by groucho75** [comment]
Hi Jeff, thanks a lot for your answer. I've just added in plugin faq oage: http://www.eventualo.net/blog/wp-alo-easymail-newsletter-faq/#faq-31

**Comment by jeffmcneill** [comment]
Awesome, thanks for including this.
